Add helm chart to proxy
giantswarm/grafana-multi-tenant-proxy pull request #152
Opened 2024-08-26 09:13 UTC by QuentinBisson

This PR:

- adds a helm chart to the proxy component so it can be deployed as a standalone

### Checklist

- [x] Update changelog in CHANGELOG.md.

2024-08-26 09:30 UTC, TheoBrigitte requested changes

2024-08-26 09:30 UTC, TheoBrigitte commented on .circleci/config.yml
> +      ## TODO replace with proper go build and push to registries
Why should we replace this with a go build ?

2024-08-26 09:30 UTC, TheoBrigitte commented on .circleci/config.yml
> +        dockerfile: ".Dockerfile-with-tests"
I would prefer that we publish a final version which do no contains tests

2024-08-26 09:30 UTC, TheoBrigitte commented on helm/grafana-multi-tenant-proxy/Chart.yaml
> +  - https://github.com/giantswarm/grafana-multi-tenant-proxy
Where is the dependency to the upstream helm chart ?

2024-08-26 09:30 UTC, TheoBrigitte commented on helm/grafana-multi-tenant-proxy/README.md
> +| fullnameOverride | string | `nil` | Overrides the chart's computed fullname |
```suggestion
| fullnameOverride | string | `null` | Overrides the chart's computed fullname |
```

2024-08-26 09:30 UTC, TheoBrigitte commented on helm/grafana-multi-tenant-proxy/README.md
> +| nameOverride | string | `nil` | Overrides the chart's name |
```suggestion
| nameOverride | string | `null` | Overrides the chart's name |
```

2024-08-26 09:30 UTC, TheoBrigitte commented on helm/grafana-multi-tenant-proxy/README.md
> +| proxy.autoscaling.targetMemoryUtilizationPercentage | string | `nil` | Target memory utilisation percentage for the multi-tenant proxy |
```suggestion
| proxy.autoscaling.targetMemoryUtilizationPercentage | string | `null` | Target memory utilisation percentage for the multi-tenant proxy |
```

2024-08-26 09:30 UTC, TheoBrigitte commented on helm/grafana-multi-tenant-proxy/README.md
> +| proxy.containerPort | int | `3501` |  |
Please add the missing description

2024-08-26 09:30 UTC, TheoBrigitte commented on helm/grafana-multi-tenant-proxy/README.md
> +| proxy.credentials | string | `"users:\n  - username: Tenant1\n    password: 1tnaneT\n    orgid: tenant-1\n  - username: Tenant2\n    password: 2tnaneT\n    orgid: tenant-2"` |  |
Please add the missing description

2024-08-26 09:30 UTC, TheoBrigitte commented on helm/grafana-multi-tenant-proxy/README.md
> +| proxy.deployCredentials | bool | `true` |  |
Please add the missing description

2024-08-26 09:30 UTC, TheoBrigitte commented on helm/grafana-multi-tenant-proxy/README.md
> +| proxy.image.tag | string | `nil` | Overrides the image tag whose default is the chart's appVersion |
How come we have `proxy.image` with an object and then `proxy.image.repository` and `proxy.image.tag` ? This is confusing to me.

2024-08-26 09:30 UTC, TheoBrigitte commented on helm/grafana-multi-tenant-proxy/README.md
> +| proxy.image.tag | string | `nil` | Overrides the image tag whose default is the chart's appVersion |
```suggestion
| proxy.image | object | `{"pullPolicy":"IfNotPresent","pullSecrets":[],"repository":"giantswarm/grafana-multi-tenant-proxy","tag":null}` | ref: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy |
| proxy.image.repository | string | `"giantswarm/grafana-multi-tenant-proxy"` | Repository to get multi-tenant proxy image from. |
| proxy.image.tag | string | `null` | Overrides the image tag whose default is the chart's appVersion |
```

2024-08-26 09:30 UTC, TheoBrigitte commented on helm/grafana-multi-tenant-proxy/README.md
> +| proxy.podSecurityContext.seccompProfile.type | string | `"RuntimeDefault"` |  |
Please add missing descriptions

2024-08-26 09:30 UTC, TheoBrigitte commented on helm/grafana-multi-tenant-proxy/templates/auth-secret.yaml
> +  name: {{ include "proxy.fullname" $ }}-auth-config
We might exceed the 63 characters limit here

2024-08-26 09:30 UTC, TheoBrigitte commented on helm/grafana-multi-tenant-proxy/templates/config.yaml
> +  name: {{ include "proxy.fullname" $ }}-config
We might exceed the 63 characters limit here

2024-08-26 09:31 UTC, QuentinBisson commented on .circleci/config.yml
> +      ## TODO replace with proper go build and push to registries
To match our usual pipelines

2024-08-26 09:31 UTC, QuentinBisson commented on .circleci/config.yml
> +      ## TODO replace with proper go build and push to registries
https://github.com/giantswarm/logging-operator/blob/fa2942c6cef40a30bd6b961217ece881960b952b/.circleci/config.yml#L10

2024-08-26 09:31 UTC, QuentinBisson commented on helm/grafana-multi-tenant-proxy/Chart.yaml
> +  - https://github.com/giantswarm/grafana-multi-tenant-proxy
There is none

2024-08-26 09:32 UTC, QuentinBisson commented on helm/grafana-multi-tenant-proxy/README.md
> +| fullnameOverride | string | `nil` | Overrides the chart's computed fullname |
That was generated by helm-docs

2024-08-26 09:33 UTC, TheoBrigitte commented on .circleci/config.yml
> +      ## TODO replace with proper go build and push to registries
Then please add it in this PR

2024-08-26 09:34 UTC, QuentinBisson commented on .circleci/config.yml
> +      ## TODO replace with proper go build and push to registries
Well this is not so easy because our go-build is too opinionated so main.go needs to be at the root of the repo

2024-08-26 09:34 UTC, TheoBrigitte commented on helm/grafana-multi-tenant-proxy/Chart.yaml
> +  - https://github.com/giantswarm/grafana-multi-tenant-proxy
Why do we have a Chart.lock file with dependencies then ?

2024-08-26 11:17 UTC, QuentinBisson commented on helm/grafana-multi-tenant-proxy/Chart.yaml
> +  - https://github.com/giantswarm/grafana-multi-tenant-proxy
I removed it

2024-08-26 11:28 UTC, QuentinBisson commented on helm/grafana-multi-tenant-proxy/templates/auth-secret.yaml
> +  name: {{ include "proxy.fullname" $ }}-auth-config
Fixed with https://github.com/giantswarm/grafana-multi-tenant-proxy/pull/152/files#diff-1e08bd35de07099af400a8bdae61da19bb99b93ba0b9c126f89a9eea94d49648R16

2024-08-26 11:28 UTC, QuentinBisson commented on helm/grafana-multi-tenant-proxy/templates/config.yaml
> +  name: {{ include "proxy.fullname" $ }}-config
Fixed with https://github.com/giantswarm/grafana-multi-tenant-proxy/pull/152/files#diff-1e08bd35de07099af400a8bdae61da19bb99b93ba0b9c126f89a9eea94d49648R16

2024-08-26 11:31 UTC, QuentinBisson commented on helm/grafana-multi-tenant-proxy/README.md
> +| proxy.podSecurityContext.seccompProfile.type | string | `"RuntimeDefault"` |  |
Should be fixed

2024-08-26 11:31 UTC, QuentinBisson commented on .circleci/config.yml
> +        dockerfile: ".Dockerfile-with-tests"
done waiting for new architect

2024-08-26 11:32 UTC, QuentinBisson commented on helm/grafana-multi-tenant-proxy/README.md
> +| proxy.image.tag | string | `nil` | Overrides the image tag whose default is the chart's appVersion |
fixed

2024-08-26 11:49 UTC, TheoBrigitte commented
Force push make it harder to follow up on review as it removes the capability to review only latest changes from last review. Please avoid this whenever possible.

2024-08-26 11:53 UTC, QuentinBisson commented
I had to rebase the master branch so I had no choice this time but I try to use it scarcely

2024-08-26 11:55 UTC, TheoBrigitte commented on helm/grafana-multi-tenant-proxy/templates/config.yaml
> +  name: {{ include "proxy.fullname" $ }}-config
Can we instead use this ?
```suggestion
  name: {{ include "proxy.fullname" $ }}
```

2024-08-26 11:55 UTC, TheoBrigitte commented on helm/grafana-multi-tenant-proxy/README.md
> +| fullnameOverride | string | `nil` | Overrides the chart's computed fullname |
`nil` does not make sense in yaml, an undefined value should be `null`.

2024-08-26 11:57 UTC, TheoBrigitte commented on Dockerfile
> +COPY pkg/ pkg/
`pkg/` does not exists

2024-08-26 11:58 UTC, TheoBrigitte commented on Dockerfile
> +# Build the grafana-multi-tenant-proxy binary
This Dockerfile is very different than the original `build/package/Dockerfile-with-tests` used, why so many differences ?

2024-08-26 12:03 UTC, QuentinBisson commented on helm/grafana-multi-tenant-proxy/README.md
> +| fullnameOverride | string | `nil` | Overrides the chart's computed fullname |
So yaml actually supports both nil and null and sure we can change this but it will be regenerated everytime we run helm-docs

2024-08-26 12:04 UTC, QuentinBisson commented on Dockerfile
> +# Build the grafana-multi-tenant-proxy binary
The original one was quite outdated and was running tests in the container while we run then in the CI so I took a jab at a better one. Want me to revert?

2024-08-26 12:04 UTC, QuentinBisson commented on Dockerfile
> +COPY pkg/ pkg/
```suggestion
```

2024-08-26 12:14 UTC, TheoBrigitte commented
Oops sorry wrong branch

2024-08-26 12:26 UTC, TheoBrigitte commented on Dockerfile
> +# Build the grafana-multi-tenant-proxy binary
No this looks fine overall

2024-08-26 12:28 UTC, QuentinBisson commented on Dockerfile
> +# Build the grafana-multi-tenant-proxy binary
This si the one generated by kubebuilder. it looked way better

2024-08-26 12:46 UTC, TheoBrigitte commented on .circleci/config.yml
> +  architect: giantswarm/architect@dev:30a70d1ee2cf158cd0ea66d74cf4b0bf930009d3
Reminder to set architect orb version once https://github.com/giantswarm/architect-orb/pull/546 is merged and released.

2024-08-26 20:20 UTC, QuentinBisson commented
This PR has been tested on gaggle using this config:

```
proxy:
      networkPolicy:
        enabled: true
        flavor: cilium
      targetServers:
        - name: loki-read
          host: grafana-multi-tenant-proxy.monitoring.svc
          target: http://loki-gateway.loki.svc.cluster.local
        - name: loki-write
          host: write.loki.gaggle.azuretest.gigantic.io
          target: http://loki-gateway.loki.svc.cluster.local
      ingress:
	enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-giantswarm
          giantswarm.io/external-dns: managed
        hosts:
          - host: write.loki.gaggle.azuretest.gigantic.io
            paths:
              - path: /loki/api/v1/push
                pathType: ImplementationSpecific
        tls:
          - hosts:
            - write.loki.gaggle.azuretest.gigantic.io
            secretName: loki-ingress-cert
```

with the following logging-operator change https://github.com/giantswarm/logging-operator/pull/198

There is however nothing preventing us from releasing this component now as it can run without any wiring yet

2024-08-26 20:39 UTC, QuentinBisson commented
And it keeps working when disabling the inner loki's auth:

```
   multiTenantAuth:
      enabled: false
    loki:
      gateway:
        nginxConfig:
          customReadUrl: ""
          customWriteUrl: ""
          customBackendUrl: ""
        # Gateway ingress configuration
        ingress:
          enabled: false
```

2024-08-29 15:41 UTC, TheoBrigitte commented on .circleci/config.yml
> +        dockerfile: ".Dockerfile-with-tests"
We are now using architect-orb@5.7.0

2024-08-29 15:41 UTC, TheoBrigitte commented on .circleci/config.yml
> +      ## TODO replace with proper go build and push to registries
We are now using architect-orb@5.7.0 with support for different path for main.go

2024-08-29 15:41 UTC, TheoBrigitte commented on .circleci/config.yml
> +  architect: giantswarm/architect@dev:30a70d1ee2cf158cd0ea66d74cf4b0bf930009d3
done

2024-08-29 15:45 UTC, TheoBrigitte approved these changes
Fine with me when tested.

2024-09-03 09:42 UTC, merged